### PR TITLE
Types

### PR DESCRIPTION
**Pull request by rfroetscher**
@timchan-lumoslabs @dollschasingmen

### CODE REVIEW

**Comment by dollschasingmen** [comment]
whats the story behind this?

**Comment by rfroetscher** [comment]
story is that when i tried to get the payment amount from the correct position it looked like this '000000001199N'

**Comment by rfroetscher** [comment]
and the dates looked like this '2015361'

**Comment by dollschasingmen** [comment]
what the shit is 000000001199N

**Comment by rfroetscher** [comment]
exactly

**Comment by dollschasingmen** [comment]
anyway, +1. good tests

**Pull request merged**
